[package]
name = "telemetry_visualizer"
version = "0.1.0"
edition = "2021"

[dependencies]
telemetry_interface = {path = "../telemetry_interface" }
eframe = "0.31.0"
egui_plot = "0.32.1"
serde = { version = "1.0.208", features = ["derive"] }
strum = { version = "0.27.1", default-features = false, features = ["derive"] }
postcard = "1.0.10"
rfd = "0.13"
csv = "1.3"