[package]
name = "bjr_on_host"
version = "0.1.0"
edition = "2021"

[dependencies]
bjr_bsp = { path = "../bjr_bsp", version = "0.1.0", features = ["mock_board"]}
os_traits = {path = "../os_traits"}
bjr_builder = { path = "../bjr_builder", version = "0.1.0"}
bjr_logic = {path = "../bjr_logic", version = "0.1.0"}
strum = { version = "0.26.3", default-features = false, features = ["derive"] }
strum_macros = "0.26.4"
embedded-time = "0.12.1"