[package]
name = "bjr_logic"
version = "0.1.0"
edition = "2021"

[dependencies]
device_traits = { path = "../device_traits", version = "0.1.0" }
os_traits = {path = "../os_traits"}
bjr_telemetry = {path = "../bjr_telemetry"}
embedded-time = "0.12.1"
heapless = "0.8.0"
atomic_float = "1.0.0"
menu = { version = "0.5.1",default-features = false }
libm = "0.2.8"
fast-math = "0.1.1"
strum = { version = "0.26.3", default-features = false, features = ["derive"] }
strum_macros = "0.26.4"
defmt = { version = "0.3.8", optional = true }
postcard = {version = "1.0.10", default-features = false}
nalgebra = {version = "0.33.0", default-features = false, features = ["libm"]}

[dev-dependencies]
mockall = "0.12.1"
[features]
defmt = ["dep:defmt", "device_traits/defmt"]
